import React from 'react';
const Slider = () => {
    return ( <>
    <button class="slick-prev slick-arrow" aria-label="Previous" type="button" style="">Previous</button>
           <div class="slick-list draggable" style="padding: 0px 200px;"><div class="slick-track" style="opacity: 1; width: 5112px; transform: translate3d(-1278px, 0px, 0px);"><div class="osahan-slider-item slick-slide slick-cloned" data-slick-index="-2" aria-hidden="true" tabindex="-1" style="width: 623px;"><img src="https://askbootstrap.com/preview/bookishow/img/slider2.jpg" class="https://askbootstrap.com/preview/bookishow/img-fluid rounded" alt="..."></div><div class="osahan-slider-item slick-slide slick-cloned" data-slick-index="-1" aria-hidden="true" tabindex="-1" style="width: 623px;"><img src="https://askbootstrap.com/preview/bookishow/img/slider3.jpg" class="https://askbootstrap.com/preview/bookishow/img-fluid rounded" alt="..."></div><div class="osahan-slider-item slick-slide slick-current slick-active slick-center" data-slick-index="0" aria-hidden="false" tabindex="0" style="width: 623px;"><img src="https://askbootstrap.com/preview/bookishow/img/slider1.jpg" class="https://askbootstrap.com/preview/bookishow/img-fluid rounded" alt="..."></div><div class="osahan-slider-item slick-slide" data-slick-index="1" aria-hidden="true" tabindex="-1" style="width: 623px;"><img src="https://askbootstrap.com/preview/bookishow/img/slider2.jpg" class="https://askbootstrap.com/preview/bookishow/img-fluid rounded" alt="..."></div><div class="osahan-slider-item slick-slide" data-slick-index="2" aria-hidden="true" tabindex="-1" style="width: 623px;"><img src="https://askbootstrap.com/preview/bookishow/img/slider3.jpg" class="https://askbootstrap.com/preview/bookishow/img-fluid rounded" alt="..."></div><div class="osahan-slider-item slick-slide slick-cloned" data-slick-index="3" aria-hidden="true" tabindex="-1" style="width: 623px;"><img src="https://askbootstrap.com/preview/bookishow/img/slider1.jpg" class="https://askbootstrap.com/preview/bookishow/img-fluid rounded" alt="..."></div><div class="osahan-slider-item slick-slide slick-cloned slick-center" data-slick-index="4" aria-hidden="true" tabindex="-1" style="width: 623px;"><img src="https://askbootstrap.com/preview/bookishow/img/slider2.jpg" class="https://askbootstrap.com/preview/bookishow/img-fluid rounded" alt="..."></div><div class="osahan-slider-item slick-slide slick-cloned" data-slick-index="5" aria-hidden="true" tabindex="-1" style="width: 623px;"><img src="https://askbootstrap.com/preview/bookishow/img/slider3.jpg" class="https://askbootstrap.com/preview/bookishow/img-fluid rounded" alt="..."></div></div></div>
           
    
    </> );
}
 
export default Slider;