export const SEARCH_MOVIE = "SEARCH_MOVIE";
export const ADD_TO_FAVOURITE = "ADD_TO_FAVOURITE";
export const REMOVE_FROM_FAVOURITE = "REMOVE_FROM_FAVOURITE";
export const GET_CURRENT_MOVIE = "GET_CURRENT_MOVIE";
export const SET_GLOBAL_SEARCH_TERM = "SET_GLOBAL_SEARCH_TERM";
export const CLEAR_SEARCH_MOVIE = "CLEAR_SEARCH_MOVIE";
export const SET_LOADING = "SET_LOADING";
